### ISSUE TITLE
Exception generated: java.lang.ClassFormatError: Absent Code attribute in method that is not native or abstract in class file javax/ws/rs/core/Response$ResponseBuilder

### ISSUE THREAD

**Issue by Phil-Jean** [jborgers/sonar-pmd#33] opened 2016-12-12 13:51 UTC
Hello,

With PMD 2.6 plugin version, the following exception is  generated. Have you an idea from where that can comes? 

Thanks,

Philippe

java.lang.ClassFormatError: Absent Code attribute in method that is not native or abstract in class file javax/ws/rs/core/Response$ResponseBuilder
       at java.lang.ClassLoader.defineClass1(Native Method)
       at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
       at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
       at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
       at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
       at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
       at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
       at java.security.AccessController.doPrivileged(Native Method)
       at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by timwebster9** [comment] 2017-01-11 14:40
hi -sorry for the late reply - can you provide some more details please?  Like when it is happening, what server version, etc...

**Comment by Phil-Jean** [comment] 2017-01-11 16:07
Hi Tim,

The problem happens on sonarqube 5.6.3 with the pmd plugin 2.6. This problem wasn’t existing on sonarqube 4.5.5 with the pmd plugin 2.4.1. The analysis is run through the maven plugin 3.2. 
Attached, a complete execution log. I hope that can help you to understand the problem.

Thanks,

Philippe

[log_ME0112.zip](https://github.com/SonarQubeCommunity/sonar-pmd/files/699351/log_ME0112.zip)

**Comment by polochon44** [comment] 2017-06-15 07:41
Hello,

In our Maven build, we have the same issue :

Caused by: java.lang.ClassFormatError: Absent Code attribute in method that is not native or abstract in class file javax/servlet/http/HttpServletResponseWrapper
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at net.sourceforge.pmd.lang.java.typeresolution.PMDASMClassLoader.loadClass(PMDASMClassLoader.java:65)

The workaround is to exclude the class.

Environment :
* Maven 3.1.1
* sonar-maven-plugin 3.3.0.603
* SonarQube version  5.6.5
* PMD 5.4.2
* maven.compiler.source/target 1.6

Cdlt.

**Comment by subisueno** [comment] 2017-06-19 12:09
I did not get your workaround, excluding the class means what ? Because in my case Response.Status is used in so many classes. I faced same issue -
Waiting for Jenkins to finish collecting data
[ERROR] Failed to execute goal org.codehaus.mojo:sonar-maven-plugin:2.7.1:sonar (default-cli) on project ngpscenarioplanner.futureRetail: Execution default-cli of goal org.codehaus.mojo:sonar-maven-plugin:2.7.1:sonar failed: An API incompatibility was encountered while executing org.codehaus.mojo:sonar-maven-plugin:2.7.1:sonar: java.lang.ClassFormatError: Absent Code attribute in method that is not native or abstract in class file javax/ws/rs/core/Response$Status
[ERROR] -----------------------------------------------------

**Comment by alromarques** [comment] 2018-01-10 11:07
We have the same problem. Any solution?

**Comment by pgervais70** [comment] 2018-07-04 13:20
This issue comes from pmd. 
It was fixed in version 6.4, see https://github.com/pmd/pmd/issues/1131

**Comment by Sinc63** [comment] 2018-10-01 14:12
Is there a plan to produce a new version of the PMD plugin to pick up PMD 6.4 or higher? We are moving to the latest SQ LTS and I'm hitting this error in 2.6 and need the fix. Thanks.

**Comment by jborgers** [comment] 2022-05-06 09:23
Is this still relevant or can we close it?

**Comment by jborgers** [comment] 2022-05-06 09:29
Assuming not relevant anymore. Old versions.

**Closed by jborgers** 2022-05-06 09:29 UTC
